stages:
  - build

image: docker:stable

before_script:
  - docker login --username=altwalkerbot --password=$PASSWORD

after_script:
  - docker logout

altwalker:
  stage: build
  tags:
    - docker
  script:
    - docker --help
