stages:
  - build

image: docker:stable

services:
  - docker:dind

before_script:
  - docker login --username=altwalkerbot --password=$PASSWORD

after_script:
  - docker logout

variables:
  GRAPHWALKER_VERSION: "4.0.0"
  ALTWALKER_VERSION: "0.2.7"

graphwalker:
  stage: build
  tags:
    - docker
  when: manual
  only:
    - master
  script:
    - docker build -t altwalker/graphwalker --build-arg GRAPHWALKER_VERSION=$GRAPHWALKER_VERSION ./graphwalker
    - docker tag altwalker/graphwalker altwalker/graphwalker:$GRAPHWALKER_VERSION
    - docker push altwalker/graphwalker:$GRAPHWALKER_VERSION

altwalker:
  stage: build
  tags:
    - docker
  when: manual
  only:
    - master
  script:
    - docker build -t altwalker/altwalker --build-arg ALTWALKER_VERSION=$ALTWALKER_VERSION ./altwalker
    - docker tag altwalker/altwalker altwalker/altwalker:$ALTWALKER_VERSION
    - docker push altwalker/altwalker:$ALTWALKER_VERSION
    - docker tag altwalker/altwalker altwalker/altwalker:latest
    - docker push altwalker/altwalker:latest

tests:
  stage: build
  tags:
    - docker
  when: manual
  only:
    - master
  script:
    - docker build -t altwalker/tests --build-arg DOTNET_SDK_VERSION="2.1" ./tests/dotnet
    - docker tag altwalker/tests altwalker/tests:dotnet-v2.1
    - docker push altwalker/tests:dotnet-v2.1
    - docker build -t altwalker/tests --build-arg DOTNET_SDK_VERSION="2.2" ./tests/dotnet
    - docker tag altwalker/tests altwalker/tests:dotnet-v2.2
    - docker push altwalker/tests:dotnet-v2.2
    - docker build -t altwalker/tests ./tests/model-visualizer
    - docker tag altwalker/tests altwalker/tests:model-visualizer
    - docker push altwalker/tests:model-visualizer