stages:
  - build

image: docker:stable

services:
  - docker:dind

before_script:
  - docker login --username=altwalkerbot --password=$PASSWORD

after_script:
  - docker logout

variables:
  ALTWALKER_VERSION: "0.1.1"

altwalker:
  stage: build
  tags:
    - docker
  script:
    - docker build -t altwalker/altwalker --build-arg ALTWALKER_VERSION=$ALTWALKER_VERSION ./altwalker
    - docker tag altwalker/altwalker altwalker/altwalker:$ALTWALKER_VERSION
    - docker push altwalker/altwalker:$ALTWALKER_VERSION
    - docker tag altwalker/altwalker altwalker/altwalker:latest
    - docker push altwalker/altwalker:latest