stages:
  - build

image: docker:stable

services:
  - docker:dind

before_script:
  - docker login --username=altwalkerbot --password=$PASSWORD

after_script:
  - docker logout

variables:
  GRAPHWALKER_VERSION: "4.3.1"
  ALTWALKER_VERSION: "0.2.7"

graphwalker:
  stage: build
  tags:
    - docker
  when: manual
  only:
    - master
  script:
    - docker build -t altwalker/graphwalker --build-arg GRAPHWALKER_VERSION=$GRAPHWALKER_VERSION ./graphwalker
    - docker tag altwalker/graphwalker altwalker/graphwalker:$GRAPHWALKER_VERSION
    - docker push altwalker/graphwalker:$GRAPHWALKER_VERSION
    - docker tag altwalker/graphwalker altwalker/graphwalker:latest
    - docker push altwalker/graphwalker:latest

altwalker:
  stage: build
  tags:
    - docker
  when: manual
  only:
    - master
  script:
    - docker build -t altwalker/altwalker --build-arg ALTWALKER_VERSION=$ALTWALKER_VERSION ./altwalker/base
    - docker tag altwalker/altwalker altwalker/altwalker:$ALTWALKER_VERSION
    - docker push altwalker/altwalker:$ALTWALKER_VERSION
    - docker tag altwalker/altwalker altwalker/altwalker:latest
    - docker push altwalker/altwalker:latest

altwalker-dotnet:
  stage: build
  tags:
    - docker
  when: manual
  only:
    - master
  script:
    - docker build -t altwalker/altwalker --build-arg ALTWALKER_VERSION=$ALTWALKER_VERSION --build-arg DOTNET_SDK_VERSION="2.1" ./altwalker/dotnet
    - docker tag altwalker/altwalker altwalker/altwalker:$ALTWALKER_VERSION-dotnet-2.1
    - docker push altwalker/altwalker:$ALTWALKER_VERSION-dotnet-2.1
    - docker tag altwalker/altwalker altwalker/altwalker:latest-dotnet-2.1
    - docker push altwalker/altwalker:latest-dotnet-2.1
    - docker build -t altwalker/altwalker --build-arg ALTWALKER_VERSION=$ALTWALKER_VERSION --build-arg DOTNET_SDK_VERSION="3.1" ./altwalker/dotnet
    - docker tag altwalker/altwalker altwalker/altwalker:$ALTWALKER_VERSION-dotnet-3.1
    - docker push altwalker/altwalker:$ALTWALKER_VERSION-dotnet-3.1
    - docker tag altwalker/altwalker altwalker/altwalker:latest-dotnet-3.1
    - docker push altwalker/altwalker:latest-dotnet-3.1

tests-tox:
  stage: build
  tags:
    - docker
  when: manual
  only:
    - master
  script:
    - docker build -t altwalker/tests ./tests/tox
    - docker tag altwalker/tests altwalker/tests:tox
    - docker push altwalker/tests:tox

tests-dotnet:
  stage: build
  tags:
    - docker
  when: manual
  only:
    - master
  script:
    - docker build -t altwalker/tests --build-arg DOTNET_SDK_VERSION="2.1" --build-arg GRAPHWALKER_VERSION=$GRAPHWALKER_VERSION ./tests/dotnet
    - docker tag altwalker/tests altwalker/tests:dotnet-v2.1
    - docker push altwalker/tests:dotnet-v2.1
    - docker build -t altwalker/tests --build-arg DOTNET_SDK_VERSION="3.1" --build-arg GRAPHWALKER_VERSION=$GRAPHWALKER_VERSION ./tests/dotnet
    - docker tag altwalker/tests altwalker/tests:dotnet-v3.1
    - docker push altwalker/tests:dotnet-v3.1

tests-model-visualizer:
  stage: build
  tags:
    - docker
  when: manual
  only:
    - master
  script:
    - docker build -t altwalker/tests ./tests/model-visualizer
    - docker tag altwalker/tests altwalker/tests:model-visualizer
    - docker push altwalker/tests:model-visualizer

demos-django-auth:
  stage: build
  tags:
    - docker
  when: manual
  only:
    - master
  script:
    - docker build -t altwalker/demos ./demos/django-auth
    - docker tag altwalker/demos altwalker/demos:django-auth
    - docker push altwalker/demos:django-auth
