stages:
  - build

image: docker:stable

before_script:
  - docker login --username=altwalkerbot --password=$PASSWORD

after_script:
  - docker logout

altwalker:
  stage: build
  tags:
    - docker
  script:
    - docker build -t altwalker/altwalker --build-arg ALTWALKER_VERSION="0.1.0" ./altwalker
