stages:
  - build

image: docker:stable
services:
  - docker:dind

before_script:
  - docker login --username=altwalkerbot --password=$PASSWORD

after_script:
  - docker logout

altwalker:
  stage: build
  tags:
    - docker
  script:
    - docker build -t altwalker/altwalker --build-arg ALTWALKER_VERSION="0.1.0" ./altwalker
    - docker tag altwalker/altwalker altwalker/altwalker:0.1.0
    - docker push altwalker/altwalker:0.1.0
    - docker tag altwalker/altwalker altwalker/altwalker:latest
    - docker push altwalker/altwalker:latest